function [signal, params] = generate_nlfm(cfg)
% GENERATE_NLFM  Synthesize a single nonlinear FM (NLFM) pulse.
%
% Two variants are supported and chosen at random per call:
%
%   1) 'quadratic' (probability ~0.6):
%        f_inst(t) = f_start + alpha*t + beta*t^2
%      where alpha, beta are chosen so the chirp covers a target
%      bandwidth B over the active duration T, with a quadratic
%      (parabolic) frequency law.
%
%   2) 'sinusoidal' (probability ~0.4):
%        f_inst(t) = f_c + (B/2) * sin(2*pi * t / T)
%      where f_c is the carrier center, B the peak-to-peak frequency
%      excursion, and the modulation period equals the pulse width T.
%
% Both variants are generated by integrating the instantaneous-frequency
% law analytically to obtain phase, then forming exp(j*phase). The pulse
% is normalized to unit average power on the active region and embedded
% in a fixed-length frame (cfg.N) using cfg.padding_strategy.
%
% Outputs
% -------
%   signal : (cfg.N x 1) complex double
%   params : struct with the parameters actually used
%       .class_name      = 'NLFM'
%       .variant         = 'quadratic' | 'sinusoidal'
%       .pulse_width_s   = pulse duration in seconds
%       .num_active      = pulse length in samples
%       .bandwidth_hz    = chirp bandwidth in Hz
%       .f_center_hz     = chirp center frequency in Hz
%       .direction       = 'up' or 'down' (quadratic only; '' for sin)
%       .nlfm_alpha      = linear coefficient (quadratic only)
%       .nlfm_beta       = quadratic coefficient (quadratic only)
%       .start_idx       = index where pulse begins (1-based)
%       .stop_idx        = index where pulse ends (1-based, inclusive)
%
% Notes
% -----
% - The quadratic variant uses a *purely* quadratic phase term in addition
%   to the linear one. With pure-quadratic instantaneous frequency
%   (f_inst = f0 + beta*t^2), the chirp would only sweep upward; mixing
%   linear+quadratic gives a richer parabolic shape that visibly differs
%   from LFM in the time-frequency plane.
% - Sinusoidal variant: instantaneous frequency oscillates within
%   [fc - B/2, fc + B/2]. We use exactly one period over T so the TF
%   signature is a single S-curve.

    % ------------------------------------------------------------------
    % 1) Sample pulse width
    % ------------------------------------------------------------------
    pw_min = cfg.pulse_width_s(1);
    pw_max = cfg.pulse_width_s(2);
    T = pw_min + (pw_max - pw_min) * rand();
    num_active = round(T * cfg.fs);
    num_active = min(num_active, cfg.N);

    % ------------------------------------------------------------------
    % 2) Sample chirp bandwidth (reuse LFM bandwidth range)
    % ------------------------------------------------------------------
    B_min = cfg.lfm_bandwidth_hz(1);
    B_max = cfg.lfm_bandwidth_hz(2);
    B = B_min + (B_max - B_min) * rand();

    % ------------------------------------------------------------------
    % 3) Choose center frequency with guard band
    % ------------------------------------------------------------------
    margin = 0.05 * cfg.fs;
    f_max_abs = cfg.fs/2 - margin - B/2;
    if f_max_abs <= 0
        fc = 0;
    else
        fc = -f_max_abs + 2 * f_max_abs * rand();
    end

    % ------------------------------------------------------------------
    % 4) Pick variant (quadratic 60% / sinusoidal 40%)
    % ------------------------------------------------------------------
    if rand() < 0.6
        variant = 'quadratic';
    else
        variant = 'sinusoidal';
    end

    % ------------------------------------------------------------------
    % 5) Build phase law for chosen variant
    % ------------------------------------------------------------------
    t = (0 : num_active - 1).' * cfg.Ts;     % column vector, [0, T)

    direction = '';
    nlfm_alpha = NaN;
    nlfm_beta  = NaN;

    switch variant
        case 'quadratic'
            % Random direction (up/down sweep)
            direction = 'up';
            if rand() < 0.5
                direction = 'down';
            end

            if strcmp(direction, 'up')
                f_start = fc - B/2;
                f_stop  = fc + B/2;
            else
                f_start = fc + B/2;
                f_stop  = fc - B/2;
            end

            % Mix linear + quadratic terms.
            %   f_inst(t) = f_start + alpha*t + beta*t^2
            % We want f_inst(T) = f_stop, leaving one degree of freedom
            % to choose how "curved" the law is. We parametrize the
            % curvature ratio gamma in [0.3, 0.9]:
            %   - gamma small  -> nearly linear (close to LFM)
            %   - gamma large  -> strongly curved (far from LFM)
            % With this, alpha = (f_stop - f_start)*(1-gamma)/T,
            %             beta  = (f_stop - f_start)* gamma   /T^2.
            gamma = 0.3 + 0.6 * rand();
            df = f_stop - f_start;
            nlfm_alpha = df * (1 - gamma) / T;
            nlfm_beta  = df *      gamma  / T^2;

            % Phase = 2*pi * integral(f_inst) dt
            %       = 2*pi * (f_start*t + alpha*t^2/2 + beta*t^3/3)
            phase = 2*pi * (f_start .* t ...
                           + 0.5 * nlfm_alpha .* t.^2 ...
                           + (nlfm_beta/3) .* t.^3);

        case 'sinusoidal'
            % f_inst(t) = fc + (B/2) * sin(2*pi*t/T)
            % Phase    = 2*pi * integral(f_inst) dt
            %          = 2*pi*fc*t  - (B/2)*(T) * cos(2*pi*t/T) + const
            % We drop the constant (absorbed into initial phase).
            wm   = 2*pi / T;            % modulation angular frequency
            phase = 2*pi * fc .* t ...
                   - (B / 2) * (T) .* cos(wm .* t);

        otherwise
            error('generate_nlfm:badVariant', ...
                  'Unknown variant: %s', variant);
    end

    pulse = exp(1j * phase);

    % ------------------------------------------------------------------
    % 6) Normalize active region to unit average power
    % ------------------------------------------------------------------
    if cfg.normalize_signal_power
        p = mean(abs(pulse).^2);
        if p > 0
            pulse = pulse / sqrt(p);
        end
    end

    % ------------------------------------------------------------------
    % 7) Place pulse inside fixed-length frame
    % ------------------------------------------------------------------
    [signal, start_idx, stop_idx] = pad_signal(pulse, cfg.N, ...
                                               cfg.padding_strategy);

    % ------------------------------------------------------------------
    % 8) Pack params for logging
    % ------------------------------------------------------------------
    params.class_name    = 'NLFM';
    params.variant       = variant;
    params.pulse_width_s = T;
    params.num_active    = num_active;
    params.bandwidth_hz  = B;
    params.f_center_hz   = fc;
    params.direction     = direction;
    params.nlfm_alpha    = nlfm_alpha;
    params.nlfm_beta     = nlfm_beta;
    params.start_idx     = start_idx;
    params.stop_idx      = stop_idx;
end
